### ISSUE TITLE
Guidance...

### ISSUE THREAD

**Issue by ghost** [uwm-appbrewery/edu.uwm.slideMenu#1]
Hi Guys

I'd love to use the slide menu that you've created for a Titanium project that I'm working on. Would this be possible?

Are there any guidelines as to how the widget should be implemented?

Thanks in advance

Simon

**Comment by mgostisha** [comment]
@burgons I've just issued PR #2 that has some documentation to go over installing the widget and configuring any dependent values. Hopefully that helps!
